on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf -y install --setopt=install_weak_deps=False docker
    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Validate AppStream file
      run: |
        appstreamcli validate --no-net data/io.github.vmkspv.netsleuth.metainfo.xml.in
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: netsleuth.flatpak
        manifest-path: io.github.vmkspv.netsleuth.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}